//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductMaster
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Remarks { get; set; }
    }
}
